### ISSUE TITLE
ProgressBar has no tempplate or render function

### ISSUE THREAD

**Issue by koenichiwa** [cdmoro/bootstrap-vue-3#226]
I was trying to make my own component which included Progress as a child component.
When I tried to render, the Progress component was commented and my console displayed the following message:

```
[Vue warn]: Component is missing template or render function. 
  at <BProgress value=20 min=0 max=100  ... > 
  at <SkillBar value=20 > 
  at <App>
```

After digging around a bit I think it's not the Progress component but the ProgressBar component. It doesn't have a template defined.

This was m y(redacted) code:
```vue
<template>
  <div>
    <img :src="logoSrc">
    <div>
      <BProgress :value="value" :min="0" :max="100" height="2rem" variant='succes'/>
    </div>
  </div>
</template>

<script>
import BProgress from 'bootstrap-vue-3';

export default {
  name: 'SkillBar',
  components: {
    BProgress,
  },
  props: {
    value: {
      type: Number,
      required: true,
    },
  },
  data() {
    return {
      logoSrc: '',
    };
  },
  async mounted() {
    this.logoSrc = "[someFetchedSource]"
  },
};
</script>
```

**Comment by jclijmans** [comment]
Strange, I don't see this message.
I've looked at the docs pages were b-progress is used as well as added it to app.vue and neither produce the message.

Where do you see this message? In browser console? or in your IDE

The BProgessBar has a render function but it's returned from the setup function instead of a separate render function.

Anyway, I added a dummy template for BProgressBar in PR #227., can you test this please?

**Comment by koenichiwa** [comment]
My apologies. It was litteraly the difference between:
```js
import BProgress from 'bootstrap-vue-3'; // Wrong, doesn't render
```
and
```js
import { BProgress } from 'bootstrap-vue-3'; // Good, does render
```
