### ISSUE TITLE
b-form-select has blank options since vue 3.2.24

### ISSUE THREAD

**Issue by wolix** [cdmoro/bootstrap-vue-3#249]
there are nothing,  except "html" type. but the demo code is ok. who can help me? 
![nothing2](https://user-images.githubusercontent.com/2967767/145680343-fb6c85c0-1994-4277-81c9-4a348fc069ad.png)
![nothing1](https://user-images.githubusercontent.com/2967767/145680351-405e3adc-d0d0-4824-b714-3ecba2beee63.png)
![nothing3](https://user-images.githubusercontent.com/2967767/145680358-6bcc18c8-83ea-4c1b-9937-f99059afdbb0.png)

**Comment by sfe-efficy** [comment]
Hi! The problem is not from this component, we are getting the same error and it started after update VUE from 3.2.23 to 3.2.24.

I was investigating a few and I saw that using "v-text" and "v-html" directives at same time is problematic since 3.2.24:

```
      <b-form-select-option
        v-else
        :key="`option_${index}`"
        :value="option.value"
        :disabled="option.disabled"
        v-text="option.text"
        v-html="option.html"
      />
```

But, if I try to use only v-html in this way it's ok:

```
      <b-form-select-option
        v-else
        :key="`option_${index}`"
        :value="option.value"
        :disabled="option.disabled"
        :v-html="option.html || option.text"
      />
```

I don't know if it's a bug from Vue or they changed the behaviour of using the directives "v-text" and "v-html".

https://v3.vuejs.org/api/directives.html#v-text
https://v3.vuejs.org/api/directives.html#v-html

**Comment by sfe-efficy** [comment]
I guess the problem comes from this fix in VUE:

https://github.com/vuejs/vue-next/pull/5017/files

It seems that previously the undefined attributes were ignored, but right now not.

So, maybe it's better to use only the "v-html" attribute to render the HTML or text content, and maybe we should sanitize the content from "option.text" to avoid HTML content there.

**Comment by mariusa** [comment]
Thanks @sfe-efficy for tracing the cause, confirming

@cdmoro , this is an important issue with an easy fix. Would you please address it and bump version too? 
Maybe other form components are affected too? (radio, checkbox)
Thanks!

**Comment by mariusa** [comment]
@cdmoro Carlos, please, we need this fixed and there are no other committers approved by you to this repo. Me and another person requested commit access in another thread.
