### ISSUE TITLE
BTooltip hides on dynamic title update

### ISSUE THREAD

**Issue by MrTanoshii** [cdmoro/bootstrap-vue-3#250]
Continuing #160 and https://github.com/cdmoro/bootstrap-vue-3/issues/160#issuecomment-948936230

BTooltip currently is hidden after a dynamic title change but it should retain its display state

**Comment by MrTanoshii** [comment]
Mentioning @jclijmans as you seem to have experience with it

**Comment by jclijmans** [comment]
As part of the fix for #160, I tried different approaches to get the tooltip to update dynamically, but I found no solution.
There is a trick using data-bs-original-title, but I couldn't get it to work without hiding the tooltip first.

As far as I know, this is a current limitation of bootstrap 5. See [issue 34229](https://github.com/twbs/bootstrap/issues/34229)

This issue was moved to the discussion are but no solution yet.

**Comment by MrTanoshii** [comment]
You're right. it seems this is a bootstrap v5 issue.

I see lots of commits since and a few targeting our specific issue:
https://github.com/twbs/bootstrap/commits/main/js/src/tooltip.js

The docs also point to the functionality being added
https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.1/components/tooltips.md

It should resolve itself when the next version of bootstrap is released.

----------------------

I'm not closing this issue but if a mod wants to, feel free to; else I suggest leaving it open but mark it as "won't fix".
I'll close it after bootstrap fixes it.

**Comment by MrTanoshii** [comment]
https://github.com/twbs/bootstrap/blob/d2497b0384d05af9159743d7ff58fd071d5c5cbb/js/src/tooltip.js#L337

The `setContent` method is available in the `main` branch of bootstrap but hasn't been released yet

**Comment by MrTanoshii** [comment]
Update: Bootstrap `v5.2.0` is here, I'm working on this and will make a PR when ready
