### ISSUE TITLE
Unify library into using consistent <script setup> 

### ISSUE THREAD

**Issue by VividLemon** [cdmoro/bootstrap-vue-3#401]
Normally I don't mind that some of the other components are using different Vue styles that I am. However, I encountered a situation where because they are not uniform (and I'm using true TS syntax with defineProps) that I cannot make the component I'm building true dynamic with the other component because it does not use true TS itself. -- Meaning the component uses BLink but I cannot import those props as a type -- I think a slight rewrite to make them true TS script setup syntax could make the library work better as well as offering better typings to the end user. (Some components I have found are missing typings on emits for example, providing this would be beneficial to the user.). I could start building it, as it wouldn't take too long, however, I need the go ahead for a major change on other peoples components. 
Edit: In addition to this, I think we could make it clear in the docs when one component props extends another.

**Comment by aceofwings** [comment]
I agree. I think it might make sense to target components that have tests with 'expected default structure`. This will minimize any initial conflicts/errors as the transition is made.

**Comment by kwiksilver3441** [comment]
What do you mean? Can you give an example of one?

> I agree. I think it might make sense to target components that have tests with 'expected default structure`. This will minimize any initial conflicts/errors as the transition is made.

**Comment by kwiksilver3441** [comment]
@mariusa You seem to be very consistent with merging my requests. If I were to rewrite the application to full script setup syntax, with full(er) TS support, would it be merged? This would also include removing the need for some of the utility classes for omitting props and the likewise. I just would like to know if I put in the effort to enhance the library, that it would not be immediately rejected. As it would take a bit of time. Thanks

**Comment by mariusa** [comment]
Yes, of course, that would be great! As long as the current functionality is kept (ie doesn't break existing components).
It would also help to send smaller PRs more frequent, rather than a big one once, if these changes can be split into some functional milestones. This way we also avoid conflicts with other small potential changes.
Thank you!

**Comment by kwiksilver3441** [comment]
> Yes, of course, that would be great! As long as the current functionality is kept (ie doesn't break existing components). It would also help to send smaller PRs more frequent, rather than a big one once, if these changes can be split into some functional milestones. This way we also avoid conflicts with other small potential changes. Thank you!

Okay, good. I only ask because a rewrite would take a bit of time and would be a shame for it to be wasted. I don't foresee any major issues.  Most of the code is retained and the only things to change is usually the way props and emits are defined. Some components are quite easy, some other edge cases, like some components built with render functions, or some components with nested components in them, tend to be harder. How do you think I should create these milestones?

**Comment by aceofwings** [comment]
@kwiksilver3441 several components will have test cases. Some have simple test cases that test the default initial render. I would target components with test cases first.

**Comment by kwiksilver3441** [comment]
> @kwiksilver3441 several components will have test cases. Some have simple test cases that test the default initial render. I would target components with test cases first.

I was planning on just converting alphabetically. To make things easy. I haven't reviewed any of the tests as they are somewhat rare.

**Comment by kwiksilver3441** [comment]
SFC's that require complex interfaces -- i.e. those that extend other components props. May not yet be capable of being fully transformed into script setup syntax. I elaborated on this in my last PR. But, the workarounds I attempted to use resulted in errors when trying to import the default props object of the extended component, it results in an error of `The 2nd argument of withDefaults must be an object literal.`. Many of the components can be converted easily, however, the edge cases that require extensions are simply not able to be easily updated at this time. This will hopefully get fixed in a future update of Vue. But for now, I will avoid updating complex component cases. 

In other news, those that are simple components, are growing well with some good TS enhancements.

**Comment by aceofwings** [comment]
Oh good , yeah I noticed the library is not building properly due to the several types of errors I am seeing. Is there a way to build the library circumventing the typescript errors at the moment?

**Comment by kwiksilver3441** [comment]
> Oh good , yeah I noticed the library is not building properly due to the several types of errors I am seeing. Is there a way to build the library circumventing the typescript errors at the moment?

Probably not. But j could focus on fixing them first if you'd like
