### ISSUE TITLE
missing dependency or something ?

### ISSUE THREAD

**Issue by ThibaultMagy** [cdmoro/bootstrap-vue-3#403]
Hi, I get this error :
While processing files with vuejs:vue3 (for target os.windows.x86_64):
   ...\.meteor\packages\vuejs_vue3\0.0.1\plugin.vue3.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\parser\src\parser\error.js:134:45:
   ...\node_modules\bootstrap-vue-3\src\components\BAvatar\BAvatar.vue: Unexpected token, expected "," (24:32)

```

     22 |     badgeOffset: {type: String, required: false},
     23 |     badgeTop: {type: Boolean, default: false},
   > 24 |     badgeVariant: {type: String as PropType<ColorVariant>,
   default: 'primary'},
```

Seems like it can't use "as"

**Comment by kwiksilver3441** [comment]
It's not necessarily missing a dependency. I'm not sure why this issue has not been fixed yet by someone else -- especially one with write access. I don't think the TS is actually being compiled. Regardless, I'm confused on why we are including Babel in a Vite app. 

Regardless, in order to fix this, I recommend we take a page out of the basic installation of a vite vue app with ts and change the build command to `"build": "vue-tsc --noEmit && vite build"`. doing so would require adding vue-tsc to dev dependencies. Perhaps cleaning up the dependencies and fixing up the build process and commands would be useful.
