### ISSUE TITLE
Rounded corners while using component b-input-group-append/prepend

### ISSUE THREAD

**Issue by Muiriik** [cdmoro/bootstrap-vue-3#470]
I want to use Input groups, but when using components as mentioned in https://cdmoro.github.io/bootstrap-vue-3/components/InputGroup.html#using-sub-components there are rounded corners next to input.

While using props or slots, corners adjacent  to input are squared and looks much better than rounded corners

**Comment by VividLemon** [comment]
Despite the notion that they simply "look better", it's actually not supposed to be happening. From what I've noticed is that both append/prepend contain a wrapper div which negates the `.input-group>:not(:first-child) ...` class that the inside components are supposed to have. I'll try to work on a fix.

**Comment by VividLemon** [comment]
@devhus You seem to know quite a bit about css. Is there a way to have the above css class affect deeply nested items?
psuedo it looks like this
```html
<div class="gives class">
   <next-div "blocks class">
      <last-div class="needs class">
```
In bootstrap-vue the code is like this
```html
<div class="gives class">
      <last-div class="needs class">
```
Which works. The div in the middle blocks the class from activating though. Do you know of a way to fix this?

**Comment by devhus** [comment]
I did not understand the question clearly, but will that help ?
'''css
.gives-class:has(div.needs-class){}
'''

If you can give me more context about the issue i might have a way to do it

**Comment by VividLemon** [comment]
![image](https://user-images.githubusercontent.com/31498096/192039285-442408b3-50ba-4d29-a8a7-cd2068d7f265.png)
The corners on the left side of this button should not be rounded. They should be flush with the input element. 
It's not very noticeable with one button, but this
![image](https://user-images.githubusercontent.com/31498096/192039382-6c220e76-f4c3-4226-acce-242fe71d92db.png)
Doesn't look good.

The full class is 
```css
.input-group>:not(:first-child):not(.dropdown-menu):not(.valid-tooltip):not(.valid-feedback):not(.invalid-tooltip):not(.invalid-feedback)
```
![image](https://user-images.githubusercontent.com/31498096/192039698-3b924753-5e57-487c-9aef-352081c112e6.png)
The given class does not need to go to the `input-group-append` class element, but instead, the grandchildren

The actual class comes from here https://github.com/cdmoro/bootstrap-vue-3/blob/main/packages/bootstrap-vue-3/src/components/BInputGroup/_input-group.scss#L22

This scss was written without a `BInputGroupAppend` element in mind. That is a BV3 component wrapper.

The actual element should look like this 
![image](https://user-images.githubusercontent.com/31498096/192040459-27cc96cf-3848-4973-9c7e-c893b5cef27e.png)

**Comment by devhus** [comment]
Well, let me see..

**Comment by VividLemon** [comment]
> However, other than that PR the best solution for this issue is to remove the container div that exists in BInputGroupAddon

I think this is a better idea, as I did in https://github.com/cdmoro/bootstrap-vue-3/pull/703. The need for a wrapper element was needed in BV because Vue 2 can't do multiple root nodes. As such, I removed the wrapper single root element, which removed some of the props for that component. So far everything looks correct 👀 However, there **does** exist an issue when using dropdowns in those positions, if you could possibly try to check out why https://bootstrap-vue.org/docs/components/input-group#dropdown-addons works but ours doesn't that would be nice. Sorry for making you do that extra work, but removing the wrapper element was a better idea. 

I honestly think the b-input-append and b-input-prepend classes that were stuck onto the components were actually there to push down the missing classes that caused this, but they didn't seem to exist and didn't have any affect...

To conclude, I __think__ my pr makes everything work and shouldn't cause any major issues, but honestly it feels too weird 😕

**Comment by devhus** [comment]
@VividLemon Np, I did think the same about removing the container div but, I didn't want to do it because it wasn't clear to me if was important or not, so I made a solution and give you another and it's up to you anyways 😆 
I will look into it

**Comment by devhus** [comment]
@VividLemon endless circle of PR, look into https://github.com/cdmoro/bootstrap-vue-3/pull/704

**Comment by VividLemon** [comment]
> endless circle of PR
It do really be like that
