### ISSUE TITLE
/packages/bootstrap-vue-3: 'npm run install' fails with a 'code EUNSUPPORTEDPROTOCOL' error

### ISSUE THREAD

**Issue by DavidGalicia** [cdmoro/bootstrap-vue-3#516]
After I clone the main repo and run `npm install` in `/packages/boostrap-vue-3` I see this error:

```
user0@device:~/code/bootstrap-vue-3/packages/bootstrap-vue-3$ npm install
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user0/.npm/_logs/2022-07-31T00_41_03_933Z-debug-0.log
user0@device:~/code/bootstrap-vue-3/packages/bootstrap-vue-3$
```

Here's the log file the error references:

[2022-07-31T00_41_03_933Z-debug-0.log](https://github.com/cdmoro/bootstrap-vue-3/files/9227852/2022-07-31T00_41_03_933Z-debug-0.log)

I can work around the error by removing the `"tsconfig": "workspace:*"` line from `/packages/boostrap-vue-3/package.json` and moving the `package.json` file at the root of the project to a temporary location so npm cannot read it when `npm install` is ran.

How does the `"tsconfig": "workspace:*"` line work? Is it related to npm [workspaces](https://docs.npmjs.com/cli/v8/using-npm/workspaces)? It's my first time seeing a dependency like that.

**Comment by VividLemon** [comment]
> Is it related to npm [workspaces](https://docs.npmjs.com/cli/v8/using-npm/workspaces)? It's my first time seeing a dependency like that

That it is. The real issue is this line at the bottom of the root package.json
```json
},
  "packageManager": "pnpm@7.6.0"
}
```
If you attempt to run npm i at the root, it should give a bit more clarity. 

The reason is because during the migration to workspaces, I decided to also switch to pnpm. You don't need to run `npm i` in a sub directory when using workspaces. Simply do `pnpm i` at the root and it will be taken care of. 

That style of a dependency is a workspace specific syntax, telling it to use the library "packages/tsconfig" and treat it as a dev dependency. It functions the same as any dependency, just that it is located in this local workspace.

This is pnpms workspace docs: https://pnpm.io/workspaces you can also read about pnpm there as well.

I believe you said you were running linux, there is alternative scripts that you could use to download pnpm, but if you have node, you should be able to run `corepack prepare pnpm@7.7.0 --activate` . Then, run pnpm i at the root folder. You may need to run `corepack enable` if you've never done it before. You can read https://pnpm.io/installation for linux alternatives

Do that and everything should run great. Lmk if you have any other issues migrating

**Comment by DavidGalicia** [comment]
I ran `corepack prepare pnpm@7.7.0 --activate` and `pnpm i ` and the installation worked. Thanks! I'll close the issue now.

**Comment by dagnelies** [comment]
...I ran in the same issue too ...I guess everyone trying to help or make an MR will run into this issue ...what's the benefit of this specific setup instead of plain normal npm/package.json ?

**Comment by VividLemon** [comment]
> ...I ran in the same issue too ...I guess everyone trying to help or make an MR will run into this issue ...what's the benefit of this specific setup instead of plain normal npm/package.json ?

The library does not use npm, which is why there's safeguards against trying to use npm. 

If you would like, I can explain _why_ I chose to implement pnpm, but it's the same as why someone would chose to use any other package manager that isn't npm.

**Comment by dagnelies** [comment]
Well, I just wanted to make you aware that the more familiar the environment is to others, the easier they can contribute.

I wanted to fix this broken carousel thingy but the fact that I run into errors on install, then have to search where this error comes from, then arrive here to learn that it uses another package manager, that you first have to install and learn, and so on... well, somehow the little tweak tuned into a chore where one problem leads to another. I don't blame you for that, perhaps it's worth it. I just want to emphasize that the "cost" of this alternative tooling is the "time" contributors spent on figuring this out and installing/learning the new shiny thingy.

**Comment by VividLemon** [comment]
> Well, I just wanted to make you aware that the more familiar the environment is to others, the easier they can contribute.

I'd recommend that new contributors familiarize themselves with the [contributing guide](https://github.com/cdmoro/bootstrap-vue-3/blob/main/CONTRIBUTING.md) located at the workspace root, Specifically on how to set up the workspace. 

> Only pnpm is allowed, attempting to run any other package manager tool will cause a warning error. View pnpm installation at https://pnpm.io/installation

Located near the bottom, it does also state that contributors are always free to ask for help when they are stuck. If it is taking too long to set up the workspace, posting a question or viewing this thread can make things go by a lot quicker, rather then trying to figure out everything oneself.

**Comment by aceofwings** [comment]
pnpm is a suitable alternative to npm. There is not much "cost" when choosing a package manager. Do note all vue dependencies and vite are using pnpm.
