### ISSUE TITLE
FormCheckbox switch style is broken

### ISSUE THREAD

**Issue by mariusa** [cdmoro/bootstrap-vue-3#547]
This used to work in 0.1.13
https://cdmoro.github.io/bootstrap-vue-3/components/FormCheckbox.html#individual-checkbox-switch-style

`form-switch` needs to be added to `<div class="form-check form-switch">`
https://getbootstrap.com/docs/5.2/forms/checks-radios/#switches

**Comment by mariusa** [comment]
https://github.com/cdmoro/bootstrap-vue-3/blob/main/packages/bootstrap-vue-3/src/components/BFormCheckbox/BFormCheckbox.vue

// TODO switch is not used

**Comment by VividLemon** [comment]
I see the issue, switch is used in the `getClasses` external method. It grabs the props directly and sidesteps the resolveBooleanish function. Related to https://github.com/cdmoro/bootstrap-vue-3/pull/544 , since it is boolean | string, doing only "switch", resolves the prop to an empty string, which is considered false. 

I was curious on how the switch was working at first, it didn't seem like it was used anywhere in the component. Tomorrow, I will check through each component and see if there is similar style of offloading props to a external function. If possible, while going through each of those functions, I would like to strongly type them (for example): 
getClasses on this function could be switched to
```ts
(props: {plain?: T, button?: T, inline?: T, switch?: T, size?: T) => 
``` 
It's not a necessary change, but while I'm there. My proposed changes would be that above, then pass in an object literal like so:
```ts
const classes = getClasses(props)
// to
const classes = getClasses({switch: switchBoolean.value}) // etc etc
```
This should fix all the issues. Does that sound ok to you?

**Comment by mariusa** [comment]
Yes! Thank you :)

**Comment by VividLemon** [comment]
I may have to change it up a little bit though. If you simply did ({switch: switchBoolean.value}) the classes would lose reactivity. Doing `getClasses(props)` is fine, but doing `getClasses({foo: props.foo})` will break everything. I'd just need to use `toRefs` util

**Comment by VividLemon** [comment]
This is taking a bit longer then expected. You can view some of the commits in https://github.com/VividLemon/bootstrap-vue-3/tree/master , it contains a few updates that are not limited to this issue. While attempting to strongly type the composable that caused this error, I stumbled onto needing to fix the Aria-invalid props. In some places, they were different than in others. In some places, they are not resolved the same as in others. In some, the "grammar" and "spelling" invalid attributes are not allowed. (In mdn, they are `"grammar" | "spelling" | Booleanish`)

**Comment by VividLemon** [comment]
@mariusa some of the tests I found fail because there is a strict check for `undefined`, when in the tests, the value passed in is `null`. Technically, null is not a possible value. Should these test instances be replaced with `state: null` => `state: undefined`, or should the strict checks for undefined, be replaced with loose checks for null (ie replace `eqeqeq` => `'eqeqeq': ['error', 'always', {null: 'ignore'}],` and `props.state !== undefined` => `props.state != null`. I'm leaning replace with strict checks, since null is not generally allowed.

**Comment by mariusa** [comment]
> I'm leaning replace with strict checks

Perfect, thanks!

**Comment by VividLemon** [comment]
> Perfect, thanks!

Yeah I deleted that, I was just about to add a note saying why and how I'm changing some tests.

**Comment by VividLemon** [comment]
The BFormSelect computedAriaInvalid method resolves it's aria state differently than the composable getGroupAttr(). I made a util function to unify the two, but, which of the two should they resolve to? Or should they simply be different? 

In BFormSelect the state is checked first, whereas in the composable state is checked at the end, after ariaInvalid is checked for invalid state.

Which of the two methods should be used? Or should they be separate? If they should be the same, then a test will need to be changed.

**Comment by mariusa** [comment]
> In BFormSelect the state is checked first, whereas in the composable state is checked at the end, after ariaInvalid is checked for invalid state.

Is there a best practice already recommended by others?

**Comment by VividLemon** [comment]
I'm unsure, this has to do with how we use components. Aria-invalid will be rendered when either a person attaches the `aria invalid` attribute, or automatically when the `state` is invalid. It would make sense that aria-invalid is checked first for the result of the property, then check for state to see if it is invalid. BootstrapVue checks for ariaInvalid prop first, then checks the state prop, as shown here https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/mixins/form-state.js#L38

**Comment by mariusa** [comment]
Thanks. So we should have only one/this method too?

**Comment by VividLemon** [comment]
I believe so
