### ISSUE TITLE
No validation form state inconsistency in code vs. documentation

### ISSUE THREAD

**Issue by simensol** [cdmoro/bootstrap-vue-3#554]
The [documentation](https://cdmoro.github.io/bootstrap-vue-3/components/Form.html#validation) states that `null` form validation state means:

> Displays no validation state (neither valid nor invalid)

However, both TypeScript linting and the implementation requires the use of `undefined` instead of `null` for no validation state to work. Is the the documentation that is wrong, or is it the code?

**Comment by VividLemon** [comment]
At this time the documentation is wrong. I will keep this in mind for a future update. This will require Vue 3.3 to be released. 

This may have occurred because in general, null prop values were removed in favor of unifying for undefined. However, even if I wanted to allow for an exception with allowing this particular prop to be allowed _null_, doing `Booleanish | null` as a possible type, will break the prop. It's not possible to do complex types like that before Vue 3.3 (Note, Booleanish type is a recent addition). It may be possible to make `undefined` fill in that behavior vacuum

**Comment by VividLemon** [comment]
Honestly, undefined may already behave the way you are wanting it to. `is-valid` or `is-invalid` attributes on the final element are never rendered if `state` is undefined, ariaInvalid attributes also shouldn't render if state is undefined, assuming you haven't manually set ariaInvalid

**Comment by VividLemon** [comment]
Since there has been no additional input on the thread, and it seems that `undefined` fills the vacuum that the change has left, I am going to close the issue. Reopen the thread if you have any further questions related to this issue.
