### ISSUE TITLE
How to use bootstrap modal?

### ISSUE THREAD

**Issue by rubanshah** [cdmoro/bootstrap-vue-3#574]

**Comment by neo7337** [comment]
@rubanshah to go through the implementation you can have a look at the official bootstrap for vue docs for reference.
The implementation is straight forward as mentioned there and for any props clearance you can have a look at the code : https://github.com/cdmoro/bootstrap-vue-3/blob/main/packages/bootstrap-vue-3/src/components/BModal.vue

**Comment by VividLemon** [comment]
https://github.com/cdmoro/bootstrap-vue-3/issues/491#issuecomment-1191446667

**Comment by VividLemon** [comment]
The docs are incomplete. You can review the actual code if you want things to be a little bit more in depth, but perhaps more confusing to someone that has never reviewed the code... I'd suggest reviewing the props and emits since the internals are not all to useful. In addition, this example https://github.com/cdmoro/bootstrap-vue-3/issues/491#issuecomment-1191446667 may help with getting started.

**Comment by VividLemon** [comment]
I'm going to close this as completed since there has been no additional reply, this is added, just not well documented.
