### ISSUE TITLE
BModal do not close

### ISSUE THREAD

**Issue by adrianoleiterodrigues** [cdmoro/bootstrap-vue-3#724]
BModal do not close using close button and cancel button after first open.
But after close modal using ESC or backdrop and reopen then buttons now work.

Check online: [https://stackblitz.com/edit/vue-92b3l9](https://stackblitz.com/edit/vue-92b3l9)

**Comment by VividLemon** [comment]
I'm confused on how you seemingly have access to the vBModal directive, it is never exported in the app, made globally, or imported. This seemingly has to do with the directive, because this syntax https://stackblitz.com/edit/vue-fkgkio?file=src%2FApp.vue works fine. I suggest using v-model syntax. But it is good to note that there may be an issue with the directive.

**Comment by adrianoleiterodrigues** [comment]
I'll try to use with the v-model syntax.

Thanks! :)

**Comment by VividLemon** [comment]
Honestly, the directive may be removed outright eventually to try to keep everything in Vue and not rely on the Bootstrapjs to magically solve issues.

**Comment by matheus-rodrigues00** [comment]
Hi @adrianoleiterodrigues.
I recommend you to try to use the following modal component:
https://www.npmjs.com/package/vue-js-modal
